### PR TITLE
Fix statefulset example yaml indentation

### PR DESCRIPTION
**Pull request by AnatomicJC**
Indentation in statefulset example is not correct, this commit fixes it.

### CODE REVIEW

**Review by tldusdev — COMMENTED** [review]
fixed

**Review by tldusdev — APPROVED** [review]
🚢 it

**Review by tldusdev — COMMENTED** [review]
fix my mistake

**Comment by artberger** [comment]
Hi @AnatomicJC and @tldusdev thanks so much for raising this indentation PR. Unfortunately our doc app does not support us just merging in this change here :/ so I updated the content in our IBM source repo, and it will go out with the next doc prod push. Sorry for the inconvenience, and thanks again for raising this!

**Pull request closed without merging**
